'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Advanced_checksum_utility.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Big_No() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Big_No", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Big_Yes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Big_Yes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BLGR_BLK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BLGR_BLK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BLGR_NRML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BLGR_NRML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FB_BLK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FB_BLK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FB_NRML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FB_NRML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_No() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_No", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mini_Yes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini_Yes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property peview() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("peview", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        '''&lt;html&gt;&lt;head&gt;&lt;title&gt;Hash List&lt;/title&gt;&lt;/head&gt;
        '''&lt;body&gt;
        '''    
        '''    &lt;br&gt;&lt;h4&gt;&lt;font color=&quot;White&quot;&gt;Created by using &lt;a href=&quot;https://toolslib.net/downloads/viewdownload/354-advanced-checksum-utility/&quot;&gt;Advanced checksum utility 3.0&lt;/a&gt;&lt;/h4&gt;&lt;p&gt;&lt;table border=&quot;0&quot; cellpadding=&quot;5&quot;&gt;&lt;tr bgcolor=&quot;#606060&quot;&gt;
        '''  &lt;body bgcolor=&quot;#1E1E1E&quot;&gt;
        '''&lt;th&gt;Filename
        '''&lt;th&gt;MD5
        '''&lt;th&gt;SHA-1
        '''&lt;th&gt;SHA-256
        '''&lt;th&gt;CRC32
        '''&lt;th&gt;SHA-384
        '''&lt;th&gt;SHA-512
        '''&lt;th&gt;RIPEMD-160
        '''&lt;th&gt;Full Path
        '''&lt;th&gt;Extension
        '''
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property Table() As String
            Get
                Return ResourceManager.GetString("Table", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TWTR_BLK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TWTR_BLK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TWTR_NRML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TWTR_NRML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YB_BLK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YB_BLK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YTB_NRML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YTB_NRML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
